// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo9n6Ow5Lk4FuRBLl81bawwV0ZPg6z2aM',
    appId: '1:909633604319:web:29bec0f5d1df239b17b76a',
    messagingSenderId: '909633604319',
    projectId: 'rafiq-app-95bb1',
    authDomain: 'rafiq-app-95bb1.firebaseapp.com',
    storageBucket: 'rafiq-app-95bb1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaES0WzTa4rKnKLXptYBSKdOhuudspaMg',
    appId: '1:909633604319:android:44eb352c94f737fd17b76a',
    messagingSenderId: '909633604319',
    projectId: 'rafiq-app-95bb1',
    storageBucket: 'rafiq-app-95bb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAweKFuO1wfUP6w3YeIrB57hX0OWRv5r1I',
    appId: '1:909633604319:ios:d6fcfc8885703bfb17b76a',
    messagingSenderId: '909633604319',
    projectId: 'rafiq-app-95bb1',
    storageBucket: 'rafiq-app-95bb1.firebasestorage.app',
    iosBundleId: 'com.example.rafiqGp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAweKFuO1wfUP6w3YeIrB57hX0OWRv5r1I',
    appId: '1:909633604319:ios:d6fcfc8885703bfb17b76a',
    messagingSenderId: '909633604319',
    projectId: 'rafiq-app-95bb1',
    storageBucket: 'rafiq-app-95bb1.firebasestorage.app',
    iosBundleId: 'com.example.rafiqGp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo9n6Ow5Lk4FuRBLl81bawwV0ZPg6z2aM',
    appId: '1:909633604319:web:bc82e72e95a2a6f917b76a',
    messagingSenderId: '909633604319',
    projectId: 'rafiq-app-95bb1',
    authDomain: 'rafiq-app-95bb1.firebaseapp.com',
    storageBucket: 'rafiq-app-95bb1.firebasestorage.app',
  );
}
